/**
 * Setup API - Save Configuration
 *
 * POST /api/setup
 * Saves setup configuration to .env.local file
 * Note: This is a server-side only operation and requires file system access
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  SetupConfigSchema,
  testSupabaseConnection,
  validateSupabaseKeys,
  formatEnvFile,
  getConfigurationStatus,
  SETUP_ERROR_MESSAGES,
} from '@/lib/config/secure-store';
import { writeFile } from 'fs/promises';
import { join } from 'path';

export async function POST(request: NextRequest) {
  try {
    // Check if already configured
    const currentStatus = getConfigurationStatus();
    if (currentStatus.configured) {
      return NextResponse.json(
        {
          error: {
            code: 'ALREADY_CONFIGURED',
            message: SETUP_ERROR_MESSAGES.ALREADY_CONFIGURED,
          },
        },
        { status: 400 }
      );
    }

    const body = await request.json();

    // Validate full configuration schema
    const parseResult = SetupConfigSchema.safeParse(body);

    if (!parseResult.success) {
      return NextResponse.json(
        {
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Invalid configuration format',
            details: parseResult.error.issues.map((e) => ({
              field: e.path.map(String).join('.'),
              message: e.message,
            })),
          },
        },
        { status: 400 }
      );
    }

    const config = parseResult.data;

    // Validate Supabase keys format
    const keyValidation = validateSupabaseKeys(config.supabase);
    if (!keyValidation.valid) {
      return NextResponse.json(
        {
          error: {
            code: 'INVALID_KEYS',
            message: 'Invalid Supabase keys format',
            details: keyValidation.errors.map(err => ({ message: err })),
          },
        },
        { status: 400 }
      );
    }

    // Test Supabase connection before saving
    const connectionResult = await testSupabaseConnection(config.supabase);
    if (!connectionResult.success) {
      return NextResponse.json(
        {
          error: {
            code: 'CONNECTION_FAILED',
            message: connectionResult.error || SETUP_ERROR_MESSAGES.CONNECTION_FAILED,
          },
        },
        { status: 400 }
      );
    }

    // Format and save to .env.local
    const envContent = formatEnvFile(config);
    const envPath = join(process.cwd(), '.env.local');

    try {
      await writeFile(envPath, envContent, 'utf-8');
    } catch (err) {
      console.error('Failed to write .env.local:', err);
      return NextResponse.json(
        {
          error: {
            code: 'FILE_WRITE_ERROR',
            message: 'Failed to save configuration. Please check file permissions.',
          },
        },
        { status: 500 }
      );
    }

    // Also save public site config to a TypeScript file
    const siteConfigContent = `/**
 * Site Configuration
 * Auto-generated by Setup Wizard
 */

export const siteConfig = {
  name: '${config.site.name}',
  url: '${config.site.url}',
  adminEmail: '${config.site.adminEmail}',${config.site.logoUrl ? `\n  logoUrl: '${config.site.logoUrl}',` : ''}
} as const;
`;

    const configPath = join(process.cwd(), 'src', 'config', 'site.config.ts');

    try {
      await writeFile(configPath, siteConfigContent, 'utf-8');
    } catch (err) {
      // Non-critical error, log but don't fail
      console.warn('Failed to write site.config.ts:', err);
    }

    return NextResponse.json({
      data: {
        success: true,
        message: 'Configuration saved successfully! Please restart the development server.',
        paths: {
          env: '.env.local',
          config: 'src/config/site.config.ts',
        },
      },
    });
  } catch (error) {
    console.error('Setup save error:', error);

    return NextResponse.json(
      {
        error: {
          code: 'INTERNAL_ERROR',
          message: error instanceof Error ? error.message : 'Failed to save configuration',
        },
      },
      { status: 500 }
    );
  }
}

/**
 * GET /api/setup
 * Returns current setup status (redirects to /api/setup/status)
 */
export async function GET() {
  const status = getConfigurationStatus();

  return NextResponse.json({
    data: {
      ...status,
      message: status.configured
        ? 'Setup completed'
        : 'Setup not completed yet',
    },
  });
}
